# Getting Started with PyTorch

[PyTorch](https://pytorch.org/) is:

> An open source machine learning framework that accelerates the path from research prototyping to production deployment.

In my humble opinion, PyTorch is the [sweet](https://www.youtube.com/watch?v=-h4spfuMGDI) way to solve Machine Learning problems, in the real world! The vast community allows you to work state-of-the-art models and deploy them to production in no time (relatively speaking). Let's get started!

<a href="https://github.com/curiousily/Getting-Things-Done-with-Pytorch/blob/master/04.first-neural-network.ipynb">Getting-Things-Done-with-Pytorch</a>

## PyTorch -> NumPy

Do you know NumPy? If you do, learning PyTorch will be a breeze! If you don't, prepare to learn the skills that will guide you on your journey Machine Learning Mastery!

Let's start with something simple:

In [1]:
import torch
import numpy as np

In [56]:
a = np.array([1, 2])
b = np.array([8, 9])

c = a + b
c

array([ 9, 11])

Adding the same arrays with PyTorch looks like this:

In [7]:
a = torch.tensor([1, 2])
b = torch.tensor([8, 9])

c = a + b
c

tensor([ 9, 11])

Fortunately, you can go from NumPy to PyTorch:

In [4]:
a = torch.tensor([1, 2])
a.numpy()

array([1, 2])

 and vice versa:

In [8]:
a = np.array([1, 2])
torch.from_numpy(a)

tensor([1, 2])

The good news is that the conversions incur almost no cost on the performance of your app. The NumPy and PyTorch store data in memory in the same way. That is, PyTorch is reusing the work done by NumPy.

## Tensors

Tensors are just n-dimensional number (including booleans) containers. You can find the complete list of supported data types at [PyTorch's Tensor Docs](https://pytorch.org/docs/stable/tensors.html).

So, how can you create a Tensor (try to ignore that I've already shown you how to do it)?



In [9]:
# 2 x 2
# rows x cols
torch.tensor([[1, 2], [2, 1]])

tensor([[1, 2],
        [2, 1]])

You can create a tensor from floats:

In [11]:
torch.FloatTensor([[1, 2], [2, 1]])

tensor([[1., 2.],
        [2., 1.]])

Or define the type like so:

In [14]:
# 0 -> False
torch.tensor([[1, 2], [2, 1]], dtype=torch.bool)

tensor([[True, True],
        [True, True]])

You can use a wide range of factory methods to create Tensors without manually specifying each number. For example, you can create a matrix with random numbers like this: 

In [15]:
# 3 x 2
# random values between 0 and 1
torch.rand(3, 2)

tensor([[0.6589, 0.9447],
        [0.3100, 0.7106],
        [0.6826, 0.5982]])

Or one full of ones:

In [22]:
# Generate a 3 x 2 matrix of float values
torch.ones(3, 2)
torch.zeros(3, 2)


tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

PyTorch has a variety of useful operations:

In [23]:
x = torch.tensor([[2, 3], [1, 2]])
print(x)
print(f'sum: {x.sum()}')

tensor([[2, 3],
        [1, 2]])
sum: 8


In [33]:
x = torch.tensor([[2, 3], [1, 2]])
print(x)
print(f'sum: {x[0].sum()}')

tensor([[2, 3],
        [1, 2]])
sum: 5


Get the transpose of a 2-D tensor:

In [34]:
x.t()

tensor([[2, 1],
        [3, 2]])

In [40]:
# Scalar is a single valued tensor

x = torch.tensor([1])
type(x)
x.t()

tensor([1])

Get the shape of each dimension:

In [41]:
# x = torch.rand(3, 2)

x.size()

torch.Size([1])

Generally, performing some operation creates a new Tensor:

In [49]:
x = torch.tensor([[2, 3], [1, 2]])
print(x)
y = torch.tensor([[2, 2], [5, 1]])
# y = np.array([[2, 2], [5, 1]])
print(y)
z = x.add(y)
# np.add(x, y)
z

tensor([[2, 3],
        [1, 2]])
tensor([[2, 2],
        [5, 1]])


tensor([[4, 5],
        [6, 3]])

In [54]:
# Operator Overloading
x + y

tensor([[ 8,  9],
        [16,  5]])

But you can do it in-place:

In [1]:
x.add_(y)  # overides x with the result of x+y.
x.add(y)  # produces x+y does not store it unless you put in in a variable.
x

NameError: name 'x' is not defined

Almost all operations have an in-place version - the name of the operation, followed by an underscore.

<h3>BONUS: GPU</h3>

PyTorch is very descriptive in this case. When doing more complex stuff, you would want to check the shape of your Tensors obsessively, after every operation. Just print the size!

- Running out of GPU memory: You might be leaking memory or too large of a dataset/model. Faster/better GPU always helps. But remember, you can solve really large problems with a single powerful GPU these days. Think carefully if that is not enough for you - why that is?

## References

- ["PyTorch: A Modern Library for Machine Learning" with Adam Paszke](https://www.youtube.com/watch?v=5bSAipCNqXo)
- [Recitation 1 | Your First Deep Learning Code](https://www.youtube.com/watch?v=KrCp_yPVOxs)
- [What is PyTorch?](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html)